# Form implementation generated from reading ui file '/Users/sree/First2/CS3200/project/ui_files/locations.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(222, 295)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.universities_label = QtWidgets.QLabel(self.centralwidget)
        self.universities_label.setGeometry(QtCore.QRect(60, 0, 101, 41))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.universities_label.setFont(font)
        self.universities_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.universities_label.setObjectName("universities_label")
        self.fee_label = QtWidgets.QLabel(self.centralwidget)
        self.fee_label.setGeometry(QtCore.QRect(20, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.fee_label.setFont(font)
        self.fee_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.fee_label.setObjectName("fee_label")
        self.city_box = QtWidgets.QTextEdit(self.centralwidget)
        self.city_box.setGeometry(QtCore.QRect(90, 50, 111, 31))
        self.city_box.setObjectName("city_box")
        self.state_box = QtWidgets.QTextEdit(self.centralwidget)
        self.state_box.setGeometry(QtCore.QRect(90, 100, 111, 31))
        self.state_box.setObjectName("state_box")
        self.fee_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.fee_label_2.setGeometry(QtCore.QRect(20, 100, 51, 31))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.fee_label_2.setFont(font)
        self.fee_label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.fee_label_2.setObjectName("fee_label_2")
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(70, 150, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.search_button.setFont(font)
        self.search_button.setObjectName("search_button")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(0, 190, 81, 31))
        self.back_button.setObjectName("back_button")
        self.shutdown_db_button = QtWidgets.QPushButton(self.centralwidget)
        self.shutdown_db_button.setGeometry(QtCore.QRect(0, 220, 151, 31))
        self.shutdown_db_button.setObjectName("shutdown_db_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 222, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.universities_label.setText(_translate("MainWindow", "Locations"))
        self.fee_label.setText(_translate("MainWindow", "City:"))
        self.city_box.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.state_box.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.fee_label_2.setText(_translate("MainWindow", "State:"))
        self.search_button.setText(_translate("MainWindow", "SEARCH"))
        self.back_button.setText(_translate("MainWindow", "Go Back"))
        self.shutdown_db_button.setText(_translate("MainWindow", "Shutdown Database"))
