# Form implementation generated from reading ui file '/Users/sree/First2/CS3200/project/ui_files/remove_from_watchlist.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(331, 232)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name_box = QtWidgets.QTextEdit(self.centralwidget)
        self.name_box.setGeometry(QtCore.QRect(80, 60, 241, 31))
        self.name_box.setObjectName("name_box")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(10, 60, 61, 31))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.name_label.setObjectName("name_label")
        self.add_watchlist_label = QtWidgets.QLabel(self.centralwidget)
        self.add_watchlist_label.setGeometry(QtCore.QRect(50, 0, 231, 41))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.add_watchlist_label.setFont(font)
        self.add_watchlist_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.add_watchlist_label.setObjectName("add_watchlist_label")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(0, 160, 81, 31))
        self.back_button.setObjectName("back_button")
        self.shutdown_db_button = QtWidgets.QPushButton(self.centralwidget)
        self.shutdown_db_button.setGeometry(QtCore.QRect(170, 160, 161, 31))
        self.shutdown_db_button.setObjectName("shutdown_db_button")
        self.remove_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_button.setGeometry(QtCore.QRect(100, 100, 121, 31))
        self.remove_button.setObjectName("remove_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 331, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name_label.setText(_translate("MainWindow", "Name:"))
        self.add_watchlist_label.setText(_translate("MainWindow", "Remove from Watchlist"))
        self.back_button.setText(_translate("MainWindow", "Go Back"))
        self.shutdown_db_button.setText(_translate("MainWindow", "Shutdown Database"))
        self.remove_button.setText(_translate("MainWindow", "Remove"))
