# Form implementation generated from reading ui file '/Users/sree/First2/CS3200/project/ui_files/search_or_watchlist.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(298, 248)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.search_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_button.setGeometry(QtCore.QRect(70, 30, 151, 31))
        self.search_button.setObjectName("search_button")
        self.watchlist_button = QtWidgets.QPushButton(self.centralwidget)
        self.watchlist_button.setGeometry(QtCore.QRect(70, 70, 151, 31))
        self.watchlist_button.setObjectName("watchlist_button")
        self.shutdown_db_button = QtWidgets.QPushButton(self.centralwidget)
        self.shutdown_db_button.setGeometry(QtCore.QRect(70, 160, 151, 31))
        self.shutdown_db_button.setObjectName("shutdown_db_button")
        self.review_button = QtWidgets.QPushButton(self.centralwidget)
        self.review_button.setGeometry(QtCore.QRect(70, 110, 151, 31))
        self.review_button.setObjectName("review_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 298, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_button.setText(_translate("MainWindow", "Search"))
        self.watchlist_button.setText(_translate("MainWindow", "University Watchlist"))
        self.shutdown_db_button.setText(_translate("MainWindow", "Shutdown Database"))
        self.review_button.setText(_translate("MainWindow", "Write Review"))
