# Form implementation generated from reading ui file '/Users/sree/First2/CS3200/project/ui_files/universities_access_db.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(508, 348)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.username_box = QtWidgets.QTextEdit(self.centralwidget)
        self.username_box.setGeometry(QtCore.QRect(150, 90, 211, 31))
        self.username_box.setObjectName("username_box")
        self.username_label = QtWidgets.QLabel(self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(60, 90, 91, 31))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.username_label.setFont(font)
        self.username_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.username_label.setObjectName("username_label")
        self.password_box = QtWidgets.QTextEdit(self.centralwidget)
        self.password_box.setGeometry(QtCore.QRect(150, 150, 211, 31))
        self.password_box.setObjectName("password_box")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(60, 150, 91, 31))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.password_label.setFont(font)
        self.password_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.password_label.setObjectName("password_label")
        self.access_db_button = QtWidgets.QPushButton(self.centralwidget)
        self.access_db_button.setGeometry(QtCore.QRect(190, 200, 131, 31))
        self.access_db_button.setObjectName("access_db_button")
        self.username_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.username_label_2.setGeometry(QtCore.QRect(120, 20, 271, 41))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.username_label_2.setFont(font)
        self.username_label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.username_label_2.setObjectName("username_label_2")
        self.shutdown_db_button = QtWidgets.QPushButton(self.centralwidget)
        self.shutdown_db_button.setGeometry(QtCore.QRect(350, 260, 151, 31))
        self.shutdown_db_button.setObjectName("shutdown_db_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 508, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.username_label.setText(_translate("MainWindow", "Username:"))
        self.password_label.setText(_translate("MainWindow", "Password:"))
        self.access_db_button.setText(_translate("MainWindow", "Access Database"))
        self.username_label_2.setText(_translate("MainWindow", "University Finder"))
        self.shutdown_db_button.setText(_translate("MainWindow", "Shutdown Database"))
