# Form implementation generated from reading ui file '/Users/sree/First2/CS3200/project/ui_files/untitled.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(492, 216)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name_box = QtWidgets.QTextEdit(self.centralwidget)
        self.name_box.setGeometry(QtCore.QRect(30, 40, 111, 31))
        self.name_box.setObjectName("name_box")
        self.code_box = QtWidgets.QTextEdit(self.centralwidget)
        self.code_box.setGeometry(QtCore.QRect(350, 40, 111, 31))
        self.code_box.setObjectName("code_box")
        self.search_code_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_code_button.setGeometry(QtCore.QRect(340, 80, 131, 31))
        self.search_code_button.setObjectName("search_code_button")
        self.universities_label = QtWidgets.QLabel(self.centralwidget)
        self.universities_label.setGeometry(QtCore.QRect(180, 0, 131, 41))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.universities_label.setFont(font)
        self.universities_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.universities_label.setObjectName("universities_label")
        self.search_name_button = QtWidgets.QPushButton(self.centralwidget)
        self.search_name_button.setGeometry(QtCore.QRect(20, 80, 131, 31))
        self.search_name_button.setObjectName("search_name_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 492, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_code_button.setText(_translate("MainWindow", "Search by Code"))
        self.universities_label.setText(_translate("MainWindow", "Locations"))
        self.search_name_button.setText(_translate("MainWindow", "Search by Name"))
