# Form implementation generated from reading ui file '/Users/sree/First2/CS3200/project/ui_files/watchlist.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(321, 245)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.remove_button = QtWidgets.QPushButton(self.centralwidget)
        self.remove_button.setGeometry(QtCore.QRect(80, 100, 171, 31))
        self.remove_button.setObjectName("remove_button")
        self.edit_notes_button = QtWidgets.QPushButton(self.centralwidget)
        self.edit_notes_button.setGeometry(QtCore.QRect(80, 60, 171, 31))
        self.edit_notes_button.setObjectName("edit_notes_button")
        self.add_to_watchlist_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_to_watchlist_button.setGeometry(QtCore.QRect(80, 20, 171, 31))
        self.add_to_watchlist_button.setObjectName("add_to_watchlist_button")
        self.shutdown_db_button = QtWidgets.QPushButton(self.centralwidget)
        self.shutdown_db_button.setGeometry(QtCore.QRect(170, 170, 151, 31))
        self.shutdown_db_button.setObjectName("shutdown_db_button")
        self.back_button = QtWidgets.QPushButton(self.centralwidget)
        self.back_button.setGeometry(QtCore.QRect(0, 170, 81, 31))
        self.back_button.setObjectName("back_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 321, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.remove_button.setText(_translate("MainWindow", "Delete From Watchlist"))
        self.edit_notes_button.setText(_translate("MainWindow", "Edit Notes"))
        self.add_to_watchlist_button.setText(_translate("MainWindow", "Add to Watchlist"))
        self.shutdown_db_button.setText(_translate("MainWindow", "Shutdown Database"))
        self.back_button.setText(_translate("MainWindow", "Go Back"))
